### ISSUE TITLE
Some places in FF I that Colored Windows are not loading 

### ISSUE THREAD

**Issue by faospark** [Silvris/FFPR-ColoredWindows#1]
![Screenshot_1231](https://user-images.githubusercontent.com/11664809/138007148-08442764-7445-4303-a992-39bfa9cdaa29.png)
Made TAS run on FFI and just noticed that certain screens the mod does not load particularly in gallery and save game screen after finishing the game

**Comment by Silvris** [comment]
I should have accounted for the gallery, but I did completely forget about the Completed Save menu. The current approach requires knowing the path of each menu, which means we completely eliminate any performance cost in exchange for potentially missing menus.
